<template><div><h2 id="parse" tabindex="-1"><a class="header-anchor" href="#parse"><span>parse</span></a></h2>
<h3 id="校验-email" tabindex="-1"><a class="header-anchor" href="#校验-email"><span>校验 email</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre class="language-typescript"><code><span class="line">    <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'-- 校验emall '</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">try</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token keyword">const</span> EmailSchema <span class="token operator">=</span> v<span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span>v<span class="token punctuation">.</span><span class="token function">string</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> v<span class="token punctuation">.</span><span class="token function">email</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">      <span class="token keyword">const</span> email <span class="token operator">=</span> v<span class="token punctuation">.</span><span class="token function">parse</span><span class="token punctuation">(</span>EmailSchema<span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">)</span></span>
<span class="line">      <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'email ===>'</span><span class="token punctuation">,</span> email<span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span>error<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>error<span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="数组类型" tabindex="-1"><a class="header-anchor" href="#数组类型"><span>数组类型</span></a></h3>
<div class="language-tsx line-numbers-mode" data-highlighter="prismjs" data-ext="tsx" data-title="tsx"><pre v-pre class="language-tsx"><code><span class="line">  <span class="token keyword">const</span> StringArraySchema <span class="token operator">=</span> v<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span>v<span class="token punctuation">.</span><span class="token function">string</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'An array is required.'</span><span class="token punctuation">)</span></span>
<span class="line">      <span class="token keyword">const</span> ObjectArraySchema <span class="token operator">=</span> v<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span>v<span class="token punctuation">.</span><span class="token function">object</span><span class="token punctuation">(</span><span class="token punctuation">{</span> key<span class="token operator">:</span> v<span class="token punctuation">.</span><span class="token function">string</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">      <span class="token keyword">const</span> theTestStringArr <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'111'</span><span class="token punctuation">,</span> <span class="token string">'123'</span><span class="token punctuation">,</span> <span class="token string">'123'</span><span class="token punctuation">]</span></span>
<span class="line">      <span class="token keyword">const</span> theTestObjArr <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">        <span class="token punctuation">{</span> key<span class="token operator">:</span> <span class="token string">'key'</span><span class="token punctuation">,</span> value<span class="token operator">:</span> <span class="token string">'value'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">{</span></span>
<span class="line">          key<span class="token operator">:</span> <span class="token string">'111'</span><span class="token punctuation">,</span></span>
<span class="line">          value<span class="token operator">:</span> <span class="token string">'222'</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token punctuation">]</span></span>
<span class="line">      </span>
<span class="line">      <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token string">'ObjectArraySchema ===>'</span><span class="token punctuation">,</span></span>
<span class="line">        v<span class="token punctuation">.</span><span class="token function">parse</span><span class="token punctuation">(</span>StringArraySchema<span class="token punctuation">,</span> theTestStringArr<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">      <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token string">'ObjectArraySchema ===>'</span><span class="token punctuation">,</span></span>
<span class="line">        v<span class="token punctuation">.</span><span class="token function">parse</span><span class="token punctuation">(</span>ObjectArraySchema<span class="token punctuation">,</span> theTestObjArr<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


