<template><div><h2 id="向上一个页面传递值" tabindex="-1"><a class="header-anchor" href="#向上一个页面传递值"><span>向上一个页面传递值</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="line">  <span class="token function">backConfirm</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token keyword">var</span> pages <span class="token operator">=</span> <span class="token function">getCurrentPages</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">      <span class="token comment">// if (pages.length > 2) {</span></span>
<span class="line">      <span class="token keyword">var</span> currPage <span class="token operator">=</span> pages<span class="token punctuation">[</span>pages<span class="token punctuation">.</span>length <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">]</span> <span class="token comment">//当前页面</span></span>
<span class="line">      <span class="token keyword">var</span> prevPage <span class="token operator">=</span> pages<span class="token punctuation">[</span>pages<span class="token punctuation">.</span>length <span class="token operator">-</span> <span class="token number">2</span><span class="token punctuation">]</span> <span class="token comment">//上一个页面</span></span>
<span class="line">      <span class="token comment">// #ifdef H5</span></span>
<span class="line">      prevPage<span class="token punctuation">.</span>$vm<span class="token punctuation">.</span>unittitle <span class="token operator">=</span> val <span class="token comment">//h5写法</span></span>
<span class="line">      <span class="token comment">// #endif</span></span>
<span class="line">  </span>
<span class="line">      prevPage<span class="token punctuation">.</span><span class="token function">setData</span><span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token literal-property property">theUnittitle</span><span class="token operator">:</span> <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token number">1</span><span class="token punctuation">}</span></span>
<span class="line">      <span class="token punctuation">}</span><span class="token punctuation">)</span> </span>
<span class="line"></span>
<span class="line">        uni<span class="token punctuation">.</span><span class="token function">navigateBack</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="获取下个页面传递过来的值" tabindex="-1"><a class="header-anchor" href="#获取下个页面传递过来的值"><span>获取下个页面传递过来的值</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="line">		<span class="token comment">//兼容小程序,获取选中的值</span></span>
<span class="line">		<span class="token comment">//#ifdef MP-WEIXIN||MP-QQ</span></span>
<span class="line">		<span class="token keyword">let</span> pages <span class="token operator">=</span> <span class="token function">getCurrentPages</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">		<span class="token keyword">let</span> currPage <span class="token operator">=</span> pages<span class="token punctuation">[</span>pages<span class="token punctuation">.</span>length <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">		<span class="token keyword">this</span><span class="token punctuation">.</span>unittitle <span class="token operator">=</span> currPage<span class="token punctuation">.</span>data<span class="token punctuation">.</span>theUnittitle<span class="token punctuation">;</span></span>
<span class="line">		<span class="token keyword">if</span> <span class="token punctuation">(</span>currPage<span class="token punctuation">.</span>data<span class="token punctuation">.</span>theUnittitle<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">			<span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">$set</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>model<span class="token punctuation">,</span> <span class="token string">'work'</span><span class="token punctuation">,</span> currPage<span class="token punctuation">.</span>data<span class="token punctuation">.</span>theUnittitle<span class="token punctuation">.</span>unitname<span class="token punctuation">)</span></span>
<span class="line">			<span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">$set</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>model<span class="token punctuation">,</span> <span class="token string">'unitid'</span><span class="token punctuation">,</span> currPage<span class="token punctuation">.</span>data<span class="token punctuation">.</span>theUnittitle<span class="token punctuation">.</span>unitid<span class="token punctuation">)</span></span>
<span class="line">			<span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">$set</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>model<span class="token punctuation">,</span> <span class="token string">'topOrganizId'</span><span class="token punctuation">,</span> currPage<span class="token punctuation">.</span>data<span class="token punctuation">.</span>theUnittitle<span class="token punctuation">.</span>topOrganizId<span class="token punctuation">)</span></span>
<span class="line">			<span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">$set</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>model<span class="token punctuation">,</span> <span class="token string">'topOrganizName'</span><span class="token punctuation">,</span> currPage<span class="token punctuation">.</span>data<span class="token punctuation">.</span>theUnittitle<span class="token punctuation">.</span>topOrganizName<span class="token punctuation">)</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line">		<span class="token comment">// #endif</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="分享" tabindex="-1"><a class="header-anchor" href="#分享"><span>分享</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="line"><span class="token operator">&lt;</span>u<span class="token operator">-</span>cell icon<span class="token operator">=</span><span class="token string">"share"</span> title<span class="token operator">=</span><span class="token string">"分享豫直先锋"</span> openType<span class="token operator">=</span><span class="token string">"share"</span> arrow<span class="token operator">-</span>direction<span class="token operator">=</span><span class="token string">"right"</span> @click<span class="token operator">=</span><span class="token string">"clickHandler"</span></span>
<span class="line">						<span class="token operator">:</span>border<span class="token operator">=</span><span class="token string">"false"</span><span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>u<span class="token operator">-</span>cell<span class="token operator">></span></span>
<span class="line"><span class="token comment">//分享</span></span>
<span class="line">    uni<span class="token punctuation">.</span>$u<span class="token punctuation">.</span>mpShare<span class="token punctuation">.</span>title <span class="token operator">=</span> <span class="token string">'豫直先锋'</span></span>
<span class="line">    uni<span class="token punctuation">.</span>$u<span class="token punctuation">.</span>mpShare<span class="token punctuation">.</span>path <span class="token operator">=</span> <span class="token string">'pages/index/index'</span></span>
<span class="line">    uni<span class="token punctuation">.</span>$u<span class="token punctuation">.</span>mpShare<span class="token punctuation">.</span>imageUrl <span class="token operator">=</span> <span class="token string">'这个分享图片和分享标题做成后台可以替换的'</span></span>
<span class="line"><span class="token comment">// #endif</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


