import comp from "F:/my-project/guoguo-notes/doc-vuepress/.vuepress/.temp/pages/Java/分页插件使用.html.vue"
const data = JSON.parse("{\"path\":\"/Java/%E5%88%86%E9%A1%B5%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8.html\",\"title\":\"Java 分页插件\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Java 分页插件\",\"date\":\"2023-5-21\",\"tags\":[\"Java\",\"插件\"],\"categories\":[\"自学篇\"]},\"headers\":[{\"level\":2,\"title\":\"首先在 pom.xml 文件中导入包\",\"slug\":\"首先在-pom-xml-文件中导入包\",\"link\":\"#首先在-pom-xml-文件中导入包\",\"children\":[]},{\"level\":2,\"title\":\"如果是低版本的 springboot 框架  使用这个\",\"slug\":\"如果是低版本的-springboot-框架-使用这个\",\"link\":\"#如果是低版本的-springboot-框架-使用这个\",\"children\":[]},{\"level\":2,\"title\":\"就可以在serviceImpl 实现类中使用了\",\"slug\":\"就可以在serviceimpl-实现类中使用了\",\"link\":\"#就可以在serviceimpl-实现类中使用了\",\"children\":[]}],\"git\":{\"updatedTime\":1725329595000,\"contributors\":[{\"name\":\"袁果锅\",\"email\":\"2914310412@qq.com\",\"commits\":2}]},\"filePathRelative\":\"Java/分页插件使用.md\",\"excerpt\":\"\\n<h2>首先在 pom.xml 文件中导入包</h2>\\n<div class=\\\"language-xml\\\" data-highlighter=\\\"prismjs\\\" data-ext=\\\"xml\\\" data-title=\\\"xml\\\"><pre class=\\\"language-xml\\\"><code><span class=\\\"line\\\"><span class=\\\"token comment\\\">&lt;!--pagehelper--&gt;</span>      </span>\\n<span class=\\\"line\\\"><span class=\\\"token tag\\\"><span class=\\\"token tag\\\"><span class=\\\"token punctuation\\\">&lt;</span>dependency</span><span class=\\\"token punctuation\\\">&gt;</span></span></span>\\n<span class=\\\"line\\\">    <span class=\\\"token tag\\\"><span class=\\\"token tag\\\"><span class=\\\"token punctuation\\\">&lt;</span>groupId</span><span class=\\\"token punctuation\\\">&gt;</span></span>com.github.pagehelper<span class=\\\"token tag\\\"><span class=\\\"token tag\\\"><span class=\\\"token punctuation\\\">&lt;/</span>groupId</span><span class=\\\"token punctuation\\\">&gt;</span></span></span>\\n<span class=\\\"line\\\">    <span class=\\\"token tag\\\"><span class=\\\"token tag\\\"><span class=\\\"token punctuation\\\">&lt;</span>artifactId</span><span class=\\\"token punctuation\\\">&gt;</span></span>pagehelper-spring-boot-starter<span class=\\\"token tag\\\"><span class=\\\"token tag\\\"><span class=\\\"token punctuation\\\">&lt;/</span>artifactId</span><span class=\\\"token punctuation\\\">&gt;</span></span></span>\\n<span class=\\\"line\\\">    <span class=\\\"token tag\\\"><span class=\\\"token tag\\\"><span class=\\\"token punctuation\\\">&lt;</span>version</span><span class=\\\"token punctuation\\\">&gt;</span></span>1.4.7<span class=\\\"token tag\\\"><span class=\\\"token tag\\\"><span class=\\\"token punctuation\\\">&lt;/</span>version</span><span class=\\\"token punctuation\\\">&gt;</span></span></span>\\n<span class=\\\"line\\\"><span class=\\\"token tag\\\"><span class=\\\"token tag\\\"><span class=\\\"token punctuation\\\">&lt;/</span>dependency</span><span class=\\\"token punctuation\\\">&gt;</span></span></span>\\n<span class=\\\"line\\\"></span>\\n<span class=\\\"line\\\"></span></code></pre></div>\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
